require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - lib/output/*
    - tmp/**/*
    - vendor/**/*

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
Layout/AlignArray:
  Enabled: true
Layout/AlignHash:
  Enabled: true
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: true
Metrics/ClassLength:
  Enabled: true
  Max: 125
Metrics/ParameterLists:
  Enabled: true
Metrics/CyclomaticComplexity:
  Enabled: true
Metrics/AbcSize:
  Enabled: true

Naming/UncommunicativeMethodParamName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/InstanceVariable:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/NumericLiterals:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/AndOr:
  Enabled: true
Style/ClassCheck:
  Enabled: true
Style/GuardClause:
  Enabled: true
Style/ClassAndModuleChildren:
  EnforcedStyle: nested
Style/GlobalVars:
  Exclude:
    - 'spec/**/*.rb'
Style/ParallelAssignment:
  Enabled: false

Security/Eval:
  Enabled: true
Security/JSONLoad:
  Enabled: true
Security/YAMLLoad:
  Enabled: true
